import React, { useState } from 'react';
import { useVoiceAnalysis } from '../hooks/useVoiceAnalysis';
import { AudioUploader } from '../components/voice/AudioUploader';
import { VoiceResult } from '../components/voice/VoiceResult';
import { ErrorBanner } from '../components/ui/ErrorBanner';
import { LoadingSpinner } from '../components/ui/LoadingSpinner';
import { analyzeMessage } from '../api/reportService';
import { MessageAnalysis } from '../types';

export function CallLogs() {
  const { result, loading, error, progress, analyze } = useVoiceAnalysis();
  const [msgText, setMsgText] = useState('');
  const [msgLoading, setMsgLoading] = useState(false);
  const [msgResult, setMsgResult] = useState<MessageAnalysis | null>(null);
  const [msgError, setMsgError] = useState<string | null>(null);

  const handleAnalyzeMessage = async () => {
    if (!msgText.trim() || msgLoading) return;
    setMsgLoading(true);
    setMsgError(null);
    setMsgResult(null);
    try {
      const data = await analyzeMessage(msgText.trim());
      setMsgResult(data);
    } catch (err: any) {
      const msg = err.message || 'Message analysis failed';
      setMsgError(msg);
      console.error('[ScamDefy][CallLogs analyzeMessage]', err);
    } finally {
      setMsgLoading(false);
    }
  };

  const msgRiskColor = (level: string) => ({
    CRITICAL: '#ef4444', HIGH: '#f97316', SUSPICIOUS: '#f59e0b', SAFE: '#22c55e',
  }[level] ?? '#94a3b8');

  return (
    <div className="screen-enter" style={{ padding: '52px 16px 80px', maxWidth: 430, margin: '0 auto' }}>
      {/* Header */}
      <div style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
          <span style={{ fontSize: 24 }}>📞</span>
          <h1 style={{ fontSize: 20, fontWeight: 800, margin: 0, fontFamily: 'Syne' }}>Voice Detector</h1>
        </div>
        <div style={{
          background: '#6366f110', border: '1px solid #6366f130', borderRadius: 8, padding: '8px 12px',
        }}>
          <p style={{ color: '#94a3b8', fontSize: 12, margin: 0, lineHeight: 1.6 }}>
            Upload a voice recording to detect if it was generated by AI or cloned from a real person.
            Protect yourself from voice phishing (vishing) attacks.
          </p>
        </div>
      </div>

      {/* Audio Uploader */}
      <div style={{ marginBottom: 16 }}>
        <AudioUploader onFile={analyze} loading={loading} progress={progress} />
      </div>

      {/* Voice error */}
      {error && (
        <div style={{ marginBottom: 12 }}>
          <ErrorBanner error={{ message: error, retryable: true }} />
        </div>
      )}

      {/* Voice Result */}
      {result && (
        <div style={{ marginBottom: 24 }}>
          <VoiceResult result={result} />
        </div>
      )}

      {/* How it works */}
      <div style={{
        background: '#111827', border: '1px solid #1e293b', borderRadius: 14, padding: 16, marginBottom: 24,
      }}>
        <p style={{ color: '#94a3b8', fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.8px', marginBottom: 14 }}>
          How it works
        </p>
        <div style={{ display: 'flex', gap: 0 }}>
          {[
            { icon: '📤', step: '1', label: 'Upload', desc: 'Drop a WAV or MP3 file' },
            { icon: '🧠', step: '2', label: 'Analyze', desc: 'CNN analyzes audio features' },
            { icon: '✅', step: '3', label: 'Verdict', desc: 'REAL or AI SYNTHETIC' },
          ].map((s, i) => (
            <div key={i} style={{ flex: 1, textAlign: 'center', padding: '0 8px', position: 'relative' }}>
              {i < 2 && (
                <div style={{
                  position: 'absolute', top: 16, right: 0, width: '50%', height: 1, background: '#1e293b',
                }} />
              )}
              <div style={{
                width: 36, height: 36, borderRadius: '50%', background: '#1a2234',
                border: '1px solid #6366f130', display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto 8px', fontSize: 18,
              }}>
                {s.icon}
              </div>
              <p style={{ color: '#f1f5f9', fontSize: 12, fontWeight: 600, margin: 0 }}>{s.label}</p>
              <p style={{ color: '#94a3b8', fontSize: 10, margin: '2px 0 0', lineHeight: 1.4 }}>{s.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Message Scanner */}
      <div>
        <p style={{ color: '#f1f5f9', fontSize: 15, fontWeight: 600, margin: '0 0 12px', fontFamily: 'Syne' }}>
          💬 Message Scanner
        </p>
        <p style={{ color: '#94a3b8', fontSize: 12, margin: '0 0 12px', lineHeight: 1.6 }}>
          Paste a suspicious SMS or WhatsApp message to check for scam patterns.
        </p>
        <textarea
          value={msgText}
          onChange={e => setMsgText(e.target.value)}
          placeholder='E.g. "Your KYC has expired. Click here to verify or your account will be blocked..."'
          rows={4}
          style={{
            width: '100%', background: '#111827', border: '1px solid #1e293b',
            borderRadius: 10, padding: '12px 14px', color: '#f1f5f9', fontSize: 13,
            resize: 'vertical', marginBottom: 10, lineHeight: 1.6,
            transition: 'border-color 0.2s',
          }}
          onFocus={e => (e.target.style.borderColor = '#6366f1')}
          onBlur={e => (e.target.style.borderColor = '#1e293b')}
        />
        <button
          onClick={handleAnalyzeMessage}
          disabled={!msgText.trim() || msgLoading}
          style={{
            width: '100%', background: !msgText.trim() || msgLoading ? '#1e293b' : '#6366f1',
            color: !msgText.trim() || msgLoading ? '#475569' : '#fff',
            border: 'none', borderRadius: 10, padding: '12px 0',
            fontSize: 14, fontWeight: 600, cursor: !msgText.trim() || msgLoading ? 'not-allowed' : 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, marginBottom: 12,
          }}>
          {msgLoading ? <><LoadingSpinner size="sm" color="#94a3b8" /> Analyzing...</> : '🔍 Analyze Message'}
        </button>

        {msgError && (
          <ErrorBanner error={{ message: msgError, retryable: true }} onRetry={handleAnalyzeMessage} />
        )}

        {msgResult && (
          <div className="slide-up" style={{
            background: '#111827', borderRadius: 14, padding: 16,
            border: `1px solid ${msgRiskColor(msgResult.risk_level)}30`,
            boxShadow: `0 0 20px ${msgRiskColor(msgResult.risk_level)}10`,
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 }}>
              <div>
                <span style={{
                  fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.8px',
                  color: msgRiskColor(msgResult.risk_level),
                  background: `${msgRiskColor(msgResult.risk_level)}15`,
                  border: `1px solid ${msgRiskColor(msgResult.risk_level)}30`,
                  padding: '3px 8px', borderRadius: 9999,
                }}>
                  {msgResult.risk_level}
                </span>
              </div>
              <p style={{ color: '#94a3b8', fontSize: 11, margin: 0 }}>{msgResult.scam_category}</p>
            </div>
            <p style={{
              color: '#f1f5f9', fontSize: 13, margin: '0 0 10px', lineHeight: 1.6,
              fontWeight: 500,
            }}>
              {msgResult.user_alert}
            </p>
            {msgResult.signals_triggered?.length > 0 && (
              <div style={{ borderTop: '1px solid #1e293b', paddingTop: 10 }}>
                <p style={{ color: '#94a3b8', fontSize: 11, margin: '0 0 6px', fontWeight: 600 }}>
                  Signals detected:
                </p>
                {msgResult.signals_triggered.slice(0, 4).map((sig, i) => (
                  <p key={i} style={{ color: '#94a3b8', fontSize: 11, margin: '2px 0' }}>
                    • {sig.name ?? sig.signal} (+{sig.points})
                  </p>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
